slackapi/slack-cli

README.md

This pull request updates the `README.md` by removing the token from the CircleCI status badge. The token was required for private repos, but no longer required because we've now a public, open sourced project 🎉 🥳 
_The token is only used for the status badge, so there's no security concern that it's part of our commit history._
* [Preview README.md](https://github.com/slackapi/slack-cli/blob/9644370ed9904eff7c5a29ce384155b50d003882/README.md)
* If you're logged into CircleCI, you can open this link in an Incognito browser window

docs(readme): remove token from CircleCI status badge after open source

---

README.md

This makes it an external link so we no longer need to host the image, which is creating an issue with the docs syncing.

docs: fix sync issue by updating README.md logo to use GitHub URL

---

.github/workflows/dependencies.yml
.github/workflows/e2e_tests.yml
.github/workflows/license_check.yml
.github/workflows/sync-docs-from-cli-repo.yml
.github/workflows/tests.yml

This PR updates the GitHub Actions workflows of this repository to use the complete semver version tag.
Fixes issues where unexpected updates can cause different behaviors when versions are left unspecified since the latest tag is often updated in releases. Example: `@4` can match `@4.32.1` and later `@4.4.4`!

build: set the complete semver version of github action steps

---

.github/MAINTAINERS_GUIDE.md
.github/cli-sdk-specification.md
cmd/datastore/datastore.go
cmd/env/env.go
cmd/externalauth/externalauth.go
cmd/function/function.go
cmd/help/help.go
cmd/project/create.go
cmd/project/create_template.go
cmd/project/samples.tmpl
cmd/root.go
cmd/triggers/generate.go
cmd/upgrade/upgrade.go
internal/api/client.go
internal/shared/types/channel.go
internal/shared/types/team.go
internal/shared/types/user.go
internal/slackerror/errors.go
internal/update/cli.go
scripts/install-dev.sh
scripts/install-windows-dev.ps1
scripts/install-windows.ps1
scripts/install.sh

🤾🏻 _Kudos to @zimeg for pointing this out!_
This pull request updates all references to https://api.slack.com to https://slack.dev, when available.
In most cases, this just prevents a redirect from happening.
The main benefit is the promote our new CHANGELOG page whenever the Slack CLI has an update:

docs: update Slack CLI and Install Scripts to use the new https://slack.dev docs

---

.circleci/config.yml

This PR escapes the branch name of pull requests for use in tests started with #36.
- Before changes: `v3.0.4-pull/38/head`
- After changes: [`v3.0.4-pull-38-head`](https://github.com/slackapi/slack-cli/releases/tag/v3.0.4-pull-38-head)

ci: escape pull request branch tag before creating releases to test

---

.circleci/config.yml
.github/MAINTAINERS_GUIDE.md
.github/workflows/e2e_tests.yml

This PR adds an option to report the status of E2E tests to PRs made from a forked branch.

ci: report test status to changes made from a forked branch

---

cmd/project/create_template.go
internal/pkg/platform/deploy.go

This pull request is another minor refactor to shore up our usage of `ctx context.Context`. It removes 2 low-hanging fruit 🍒 references to `context.Background()`.
There are at least 2 more areas that need to be updated in future PRs, but they will require broader refactors to carry the context over. So, I'll leave those for separate PRs to make the reviewing easier 😎

refactor: remove context.Background() references from create and deploy

---

cmd/triggers/create.go
cmd/triggers/create_test.go
cmd/triggers/generate.go
cmd/triggers/generate_test.go
cmd/triggers/update.go

_Context delivery, get it while it's hot!_ 💁🍕 
This pull request updates the `trigger` command to no longer use `context.Background()`. Not too exciting, but I've separated this into a single PR because its changes span a few files

refactor: remove context.Background() references from triggers command

---

.github/workflows/delete-pr-build-on-close.yml

This PR uses either an upstream or fork PR branch when deleting a pre-release after a pull request is merged.
Fixes an issue where upstream tag names use different convention from forks and also where this workflow runs.

ci: delete testing fork pre-releases using upstream tag names

---

ci/circleci/runner/src/circlerunner.py
ci/circleci/runner/src/macrunner.py
cmd/auth/login_test.go
cmd/datastore/query_test.go
cmd/manifest/validate.go
cmd/project/create_samples.go
internal/api/workflows_test.go
internal/app/app.go
internal/app/app_client_test.go
internal/cmdutil/flags.go
internal/config/manifest_test.go
internal/config/system_test.go
internal/hooks/script_test.go
internal/iostreams/reader.go
internal/logger/logevent.go
internal/pkg/apps/install.go
internal/pkg/platform/activity_test.go
internal/prompts/app_select.go
internal/prompts/app_select_test.go
internal/slackerror/error.go
internal/update/autoupdate_test.go
internal/update/cli_autoupdate.go

This pull request resolves typos and misspellings in this project.

docs: fix misspellings (used typos-cli for detecting)

---

cmd/upgrade/upgrade.go

This PR updates outputs of the `upgrade` command to note if the latest SDK versions were checked.
Outputs now change depending on the path used 👾
```sh
$ slack version
Using slack v3.0.4
$ slack upgrade
✔ You are using the latest Slack CLI version
$ slack create asdf
$ cd asdf
$ slack upgrade
✔ You are using the latest Slack CLI and SDK versions
```
A handbuilt make of these changes might be useful for testing the shown version:
```
$ go build -ldflags="-X 'github.com/slackapi/slack-cli/internal/pkg/version.Version=3.0.4'" -o bin/slack
```
And these commands can be useful in testing cases with a `bolt` JS project:
```
$ npm install @slack/cli-hooks@1.0.0
$ npm install @slack/cli-hooks@latest
```

fix: 'upgrade' output includes SDK when inside a project dir

---

.github/MAINTAINERS_GUIDE.md
.github/workflows/dependencies.yml
.github/workflows/sync-docs-from-cli-repo.yml
docs/guides/authorizing-the-slack-cli.md

This PR uses different GitHub app tokens for updating upstream documentation and updating the `go` version.
Fixes an issue where the prior token didn't have the right [permissions](https://github.com/slackapi/slack-cli/pull/51#issuecomment-2816132217) to sync with docs. Or had the right permissions? 📚
- I'm not sure if these suffixes make the most sense - open to suggestions! - but if it seems alright I can include a note in comments or the `MAINTAINERS_GUIDE.md` about these apps? 🤔

ci: use different tokens to update docs and go version

---

.github/workflows/sync-docs-from-cli-repo.yml
docs/guides/deploying-with-the-slack-cli-and-github-actions.md

This PR opens more PRs for the **docs** [`sync`](https://github.com/slackapi/slack-cli/actions/workflows/sync-docs-from-cli-repo.yml) workflow if the workflow event happens on the `main` branch. Or if it was a `workflow_dispatch`.
Fixes an issue where changes were not being shared upstream - note no pull request link is created:
https://github.com/slackapi/slack-cli/actions/runs/14581033334/job/40897589695

ci: update upstream documentation if the event referenced on the main branch

---

cmd/root.go
main.go

This pull request is a minor refactor that updates our custom `root.Execute(ctx, cmd, clients)` to match the syntax of Cobra. 
In Cobra, when you execute with a provided context, then it should be `root.ExecuteContext(ctx, cmd, clients)`.
This is one of the last _(but not the last)_ pull requests that I'll make around context 😆

refactor: rename root.Execute to root.ExecuteContext

---

.github/workflows/delete-pr-build-on-close.yml

This PR uses environment variables to process pull request conclusions when deleting pre-releases while avoiding potential unescaped inputs.
[Reference](https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions?_bhlid=a791b2d00d1463ce9cf1d53929098a0231b0002a#using-secrets-in-a-workflow) 📚
> To escape these special characters, use quoting with your environment variables.
This PR is created on a forked branch to check the checked out workflow file used upon merge or deletion otherwise.

ci: use environment variables to process pull request conclusions

---

.github/workflows/delete-pr-build-on-close.yml
.github/workflows/dependencies.yml
.github/workflows/e2e_tests.yml
.github/workflows/license_check.yml
.github/workflows/sync-docs-from-cli-repo.yml
.github/workflows/tests.yml
CHANGELOG.txt

This PR sets the minimum amount of permission needed for each workflow without breaking the existing steps setup.
Testing is happening within this PR and notes left below! 👾

ci: set minimum amount of permission needed for each workflow

---

Makefile

This PR removes references to outdated build artifacts and confusing comments from outputs of `make` commands.
```diff
$ make build
golangci-lint run
0 issues.
- rm -f ./slack
- rm -f ./slack-cli
- rm -f ./hermes
rm -rf ./bin/
rm -rf ./dist/
mkdir bin/
- # set version using the latest tag plus short revision
go build -ldflags="-X 'github.com/slackapi/slack-cli/internal/pkg/version.Version=`git describe --tags --match 'v*.*.*'`'" -o bin/slack
SLACK_DISABLE_TELEMETRY="true" ./bin/slack version --skip-update
Using slack v3.0.5-6-g7656d42
```

build: remove paths to outdated artifacts in makefile clean

---

internal/slackcontext/slackcontext.go

This pull request adds a comment block above `package slackcontext` inspired by Golang's `package context` to describe the purpose and usage of `slackcontext`. Most importantly, I wanted to mention that all values should be set before the execution of a command - we may change this opinion in the future, but for now it's how we're approaching the usage of `ctx`.
❓ Should be this be labelled as "docs" or "code health"? It's an internal docs, not too different from something like `MAINTAINERS_GUIDE.md`.

docs: add comment block to package slackcontext

---

cmd/root.go

This pull request fixes a bug in our root command's execution (`.ExecuteContext(...)`) that could cause the Slack CLI to hang indefinitely. However, AFAIK, it's very unlikely for the Slack CLI to hit the edge case to cause the indefinite hang.
The core problem is that `<-ctx.Done()` was not handled, so any cancelled context would cause the Slack CLI to hang waiting for a channel completion or interrupt signal event.
> Fixes a rare edge-case that causes the Slack CLI to hang without exiting the process. Now, the Slack CLI will exit with the correct error code and allow sub-processes to cleanup.
We don't have tests for this area of the code. I started to add tests, but it requires more refactoring that led to a messy PR. So, I'll save that work for a follow-up PR.
If you want to manually …

fix: edge-case where cancelled context causes process to hang

---

cmd/root.go
cmd/root_test.go

This pull request adds 2 test-cases to `cmd.ExecuteContext`:
* Command successfully executes
* Command returns an error
We do not test the following test-cases yet because they're a little tricky:
* Interrupt Signal (CTRL+C)
* Cancelled context

test: add success and error tests to cmd.ExecuteContext

---

cmd/root_test.go
internal/iostreams/iostreams_mock.go
internal/shared/clients_mock.go
internal/tracking/tracking_mock.go

This pull request is a follow-up for https://github.com/slackapi/slack-cli/pull/61#discussion_r2059054925 that asserts `cmd.ExecuteContext` flushes the correct exit code to Logstash.
In order for this to work, we needed to fix the implementation of the `EventTrackerMock` by adding a few missing functions, writing it up to `ClientsMock`, and adding default mocks to allow our existing tests to pass.
I think we're at the point where we can test Logstash flushes throughout the code! 🎉

test: assert cmd.ExecuteContext flushes exit code to logstash

---

cmd/feedback/feedback.go
cmd/feedback/feedback_test.go

> Updated `feedback` command to display a prompt for Slack CLI feedback. Now developers can ask questions, submit issues, or suggest features for the Slack CLI through GitHub Issues.
This pull request updates the `feedback` command to display a prompt with 2 choices:
1. Slack CLI
2. Slack Platform
While expanding `feedback` to display multiple options, there are a lot of improvements that we can make. However, I've tried to scope this PR to only adding the 2nd option and tweaking things to look & feel alright. 
**The main changes are:**
* **Added option for "Slack CLI Feedback"**
* **Renamed the original option to "Slack Platform Feedback"**
* Previously, it was "Help make the Slack platform better"
* **Added a `Never` frequency**
* So that the Slack CLI Feedback is never, randomly asked …

feat: update 'feedback' command to include feedback about the Slack CLI

---

cmd/root_test.go
internal/pkg/version/version.go

This pull request fixes tests that require a valid semver from failing when using VSCode/Cursor.
Previously, tests in the following packages would fail:
* `cmd/root_test.go`
* `cmd/doctor/doctor_test.go`
* `cmd/version/version_test.go`
If we want to take this work a step further, we could update our `.circleci` pipeline to validate that the `BUILD_VERSION` does not contain `v0.0.0`. However, locally, I think we want the build to remain loose, so that developers can build the CLI even when their local repo doesn't contain git tags.
Testing:
* All unit tests should continue to pass when using `make test`
* Running file/package tests in one of the above files in VSCode should now pass

test: fix failing version tests if compilation flags are not provided

---

cmd/feedback/feedback.go
cmd/feedback/feedback_test.go
internal/slackerror/errors.go

> Updates the `feedback` command error message for a missing `--name <id>` flag to clarify that the name is specified as a flag: "Please provide a --name flag or remove the --no-prompt flag"
This pull request refactor the `feedback` command based on reviewer feedback on PR #66:
* Always use `slacktrace.FeedbackMessage` and simplify the `SurveyStore` (Commit f373184)
* Tests `slacktrace.FeedbackMessage` usage (Commit f373184)
* Adds `slackerror.FeedbackNameInvalid` and `slackerror.FeedbackNameRequired` (Commit b635bca)
Future work:
* In a future PR, I'd like to improve the test coverage of the `feedback` command

refactor: 'feedback' command trace and error handling

---

cmd/feedback/feedback.go
cmd/feedback/feedback_test.go
internal/slackerror/errors.go

> Replaces `feedback --name platform-improvements` with `feedback --name slack-platform` as the flag name for Slack Platform support. You can continue to use `--name platform-improvements` until the next major version release.
This pull request replaces `feedback --name platform-improvements` with `feedback --name slack-platform`:
* Deprecates `feedback --name platform-improvements`
* Removes `platform-improvements` from the help documentation
* Adds `feedback --name slack-platform`
* Backwards compatible with `--name platform-improvements` continues to work until the next semver:major update
```bash
$ slack feedback --help
$ slack feedback --name slack-platform
$ slack feedback --name platform-improvements
$ slack feedback --name platform-improvements --verbose
```

feat: add support for 'feedback --name slack-platform'

---

.golangci.yml
cmd/auth/login.go
cmd/root.go
cmd/root_test.go
internal/cmdutil/project.go
internal/hooks/sdk_config.go
internal/hooks/sdk_config_test.go

This pull request enables the linter `staticcheck` rule [ST1008: 'A function’s error value should be its last return value'](https://staticcheck.dev/docs/checks/#ST1008).
✅ `func HelloWorld (string, error)`
❌ `func HelloWorld (error, string)`

refactor: enable linter rule ST1008 for 'error should be last return value'

---

.golangci.yml
internal/api/client.go
internal/auth/auth.go
internal/pkg/create/create.go
internal/pkg/platform/localserver.go
internal/style/template.go
internal/update/cli_metadata.go

This pull request enables the linter `staticcheck` rule [`ST1005: 'Incorrectly formatted error string'`](https://staticcheck.dev/docs/checks#ST1005).
In general, it's enforces the following:
* Error strings must start with a lowercase letter, unless a proper name or initialism
* Unfortunately, I couldn't figure out how to make "Slack" a recognized noun
* Error strings cannot end with punctuation (e.g. periods `.`)

refactor: enable linter rule ST1005 for error string formatting

---

.github/MAINTAINERS_GUIDE.md
internal/config/project.go
internal/pkg/create/create_test.go
internal/shared/clients.go

This pull request is a follow-up from PR #70 that adds documentation around deprecating a feature in code:
* Updates `MAINTAINERS_GUIDE.md` explaining how to deprecate a public and internal feature
* Updates `// TODO(semver:major):` to `// DEPRECATED(semver:major):`
We're aligning on `// DEPRECATED:` and `// DEPRECATED(semver:major):` because [Golang appears to use a similar convention](https://cs.opensource.google/search?q=Deprecated:%20language:go&ss=go%2Fgo). If anyone thinks we should use a different convention, happy to hear it! 👂🏻

docs: add docs for deprecating a feature

---

cmd/app/add_test.go
cmd/app/delete_test.go
cmd/app/link.go
cmd/app/link_test.go
cmd/app/uninstall_test.go
cmd/auth/login_test.go
cmd/auth/logout.go
cmd/auth/logout_test.go
cmd/auth/revoke.go
cmd/auth/revoke_test.go
cmd/auth/token_test.go
cmd/doctor/check.go
cmd/doctor/doctor_test.go
cmd/manifest/validate.go
cmd/manifest/validate_test.go
cmd/project/init_test.go
cmd/root.go
internal/pkg/apps/delete.go
internal/pkg/apps/delete_test.go
internal/pkg/apps/list.go
internal/pkg/apps/list_test.go
internal/pkg/auth/list.go
internal/pkg/auth/list_test.go
internal/pkg/auth/login.go
internal/pkg/platform/deploy.go
internal/prompts/app_select.go
internal/prompts/app_select_test.go
internal/shared/clients.go
internal/shared/clients_mock.go
main.go

This pull request follows #77 by updating `clients.AuthInterface()` to `clients.Auth()`.
The motivation is that the name is shorter and more accurate. The `clients.Auth()` returns an instance of `auth.Client` that implements the `auth.AuthInterface` interface. It doesn't return an interface.
There was no change functionality was changed, but our mocks were updated to match the same naming pattern.

refactor: rename clients.AuthInterface() to clients.Auth()

---

cmd/app/add_test.go
cmd/manifest/info_test.go
docs/guides/using-slack-cli-with-bolt-frameworks.md
docs/reference/experiments.md
internal/experiment/experiment.go
internal/pkg/apps/install_test.go

> Added the experiment `--experiment bolt-install` to enable creating, installing, and running Bolt projects that manage their app manifest on app settings (remote manifest).
This pull request adds the `--experiment bolt-install` to begin work on creating, installing, and running Bolt projects that manage their app manifest on app settings (remote manifest).
The following changes were made:
* Added the `BoltInstall` experiment name
* Cast the `BoltFramework` experiment as `Experiment` instead of `String`, causing updates to tests
* Added `bolt-install` to the experiment documentation
@zimeg @lukegalbraithrussell @technically-tracy **How should we document the `--experiment bolt-install`?** 
We learned from the `bolt` experiment that it was difficult to track changes across multiple …

feat(bolt-install): added --experiment=bolt-install

---

scripts/install-dev.sh
scripts/install.sh

Hi,  
This PR improves the console output in the Deno installation part by adjusting the version check logic to handle string values (e.g., v2.3.1). Replaced numeric comparison with a neutral string check. Thanks.

fix: parse the latest deno release in installation script outputs as a tagged version

---

.github/workflows/delete-pr-build-on-close.yml
.github/workflows/dependencies.yml
.github/workflows/e2e_tests.yml
.github/workflows/license_check.yml
.github/workflows/sync-docs-from-cli-repo.yml
.github/workflows/tests.yml

This PR uses the wonderful [`zizmor`](https://github.com/zizmorcore/zizmor) tool to audit our own workflows and [`pinact`](https://github.com/suzuki-shunsuke/pinact) for pinned versioning 👾
A similar audit can be performed with the zizmor tool:
```
$ zizmor .
...
No findings to report. Good job! (1 ignored, 7 suppressed)
```
> The suppressed findings are expected permission blocks at the top-level of a workflow, but we set this for each job.
Most changes I hope are repetitive, but I will comment on the more significant ones!

ci: pin action hashes and escape variables with minimum permission

---

internal/api/icon_test.go
internal/hooks/hook_executor_v2.go

This PR replaces longform loop expressions with a shorthand range when iterating across integers starting from zero.
No change to functionalities!
- 📚 https://go.dev/wiki/Range
- AFAICT the following is not supported in `go`. Perhaps for good reason I believe:
```go
for i := range 1..100 { /* */ }
```

refactor: loop over a range of integers starting from zero in shorthand

---

.circleci/config.yml
.github/MAINTAINERS_GUIDE.md
.github/workflows/delete-pr-build-on-close.yml

This PR updates the feature tag workflow to prefer building on branches of a pull request. 👾 
- Reasons and motivation for these changes will be commented below, but this unlocks testing changes of
#124 🤖 ✨

build: share releases of feature tags for install from pull requests

---

internal/slackerror/errors.go

This error has unescaped `<` in its description which our docs sites does not like.

docs: surround remediation flags with backticks for prompted feedback

---

scripts/install-dev.sh
scripts/install-windows-dev.ps1
scripts/install-windows.ps1
scripts/install.sh

> **Changelog**
>
> The installation scripts now make a kind request for feedback in issues if the installation scripts error.
This PR outputs a link to the issue tracker if installation scripts fail. Following reported errors of #147.
With these changes change the environment for testing:
```sh
$ ./scripts/install.sh           # Might error if another "slack" program exists
$ ./scripts/install.sh lack-dev  # Succeeds
$ chmod -w /usr/local/bin        # Remove permissions needed for install
$ ./scripts/install.sh lack-dev  # Errors
$ chmod +w /usr/local/bin        # Revert changes made during this testing
```
Before requesting a review I plan to make similar changes on Windows.

feat: output a link to the issue tracker if installation scripts fail

---

.github/MAINTAINERS_GUIDE.md
.github/cli-sdk-specification.md
cmd/datastore/datastore.go
cmd/env/env.go
cmd/externalauth/externalauth.go
cmd/function/function.go
cmd/help/help.go
cmd/project/create.go
cmd/root.go
cmd/triggers/generate.go
docs/reference/commands/slack.md
docs/reference/commands/slack_datastore.md
docs/reference/commands/slack_env.md
docs/reference/commands/slack_external-auth.md
docs/reference/commands/slack_function.md
internal/slackerror/errors.go
internal/update/cli.go
scripts/install-dev.sh
scripts/install-windows-dev.ps1
scripts/install-windows.ps1
scripts/install.sh

Update the Slack CLI output to use the new https://docs.slack.dev/tools URL instead of the previous https://tools.slack.dev URL.
This pull request updates some Slack CLI output that references https://tools.slack.dev/ to now be https://docs.slack.dev/tools/.

docs: update tools.slack.dev refs to docs.slack.dev/tools

---

internal/deputil/url.go
internal/deputil/url_test.go
internal/pkg/create/create_test.go
internal/slackhttp/http.go
internal/slackhttp/http_mock.go

> Fix a bug to allow new projects to be created quicker by using a HTTP HEAD request to check if the template URL exists.
This pull request updates the `URLChecker(http, url)` to check if the URL exists using a `HEAD` request instead of a `GET` request. This should improve performance, since it will not download the zip to only confirm that the URL is valid.
There should be no change to functionality.
```bash
$ lack create asdf
$ rm -rf asdf/
```

fix: URL checker uses HEAD instead of GET

---

Makefile

This PR adds a `make tag` build command for tagging releases with updates to the docs happening in the commit being tagged 🏁 
The ellipse output takes great inspiration from https://github.com/slackapi/slack-cli/pull/224 👾 ✨ 
```
$ make tag RELEASE_VERSION=3.7.0-example
...
git tag v3.7.0-example
```
````diff
diff --git a/docs/guides/installing-the-slack-cli-for-mac-and-linux.md b/docs/guides/installing-the-slack-cli-for-mac-and-linux.md
index 124d64f..a0f7d2e 100644
--- a/docs/guides/installing-the-slack-cli-for-mac-and-linux.md
+++ b/docs/guides/installing-the-slack-cli-for-mac-and-linux.md
@@ -99,11 +99,11 @@ Manual installation allows you to customize certain paths used when installing t
**2\. Download the** `slack` **CLI installer for your environment.**
-🍎 ⚡️ [**Download for macOS …
```

build: make releases with a "make tag" build command

---

Makefile

This PR follows up on #228 and adds the `docgen` command to the "make tag" release script. Might substitute #197?
https://github.com/user-attachments/assets/f2a0c1c7-bfe7-4fad-8b85-127dffe3084d
Please feel free to comment out the "diff" and  "commit" and "tag" steps for fast testing:
```diff
diff --git a/Makefile b/Makefile
index e6d9c24..dca25b0 100644
--- a/Makefile
+++ b/Makefile
@@ -77,8 +77,8 @@ build-snapshot: clean
.PHONY: tag
tag:
-	git diff --quiet --cached
-	git diff --quiet
+	# git diff --quiet --cached
+	# git diff --quiet
@if echo "$(RELEASE_VERSION)" | grep -q '^v'; then \
echo "Error: Release version should not begin with a version prefix."; \
exit 1; \
@@ -99,6 +99,6 @@ tag:
git add docs/guides/installing-the-slack-cli-for-mac-and-linux.md
git add …
```

build: run the docgen command with make tag release

---

docs/guides/uninstalling-the-slack-cli.md

Fixes a reported broken link for uninstalling an app.

docs: fix broken link to removing an app pages
